services:
  - type: web
    name: consola-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.11
    envVars:
      - key: SECRET_KEY
        value: clave_secreta
    plan: free